version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - "**/*"
